### ISSUE TITLE
Densenet

### ISSUE THREAD

**Issue by sgjungs** [Prakhar998/food-101#1]
Hi, I'm trying to train your model in "food101.ipynb".
But I have some problems with training.

1. Which Dataset did you use and how did you split it
2. It seems that Densenet121 was used (not 161)
3. Test accuracy doesn't rise from 0.6
4. You trained at 1050ti, can i train at 1650(notebook)?

thankyou

**Comment by Prakhar998** [comment]
I am using food 101 dataset
check it on tensorflow web to download
I used both 121 and 161 but for reasons I dno`t want to publish 161 here.
you could use even 940mx also colab
